version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: cherubimis_db
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # Optional: external port mapping for local dev
    volumes:
      - db_data:/var/lib/mysql
      - ./db-primary/init-primary.sh:/docker-entrypoint-initdb.d/init-primary.sh:ro
    networks:
      - cyber_network

  web:
    build:
      context: ./cherubimis_website
      dockerfile: Dockerfile
    container_name: cherubimis_website
    env_file: .env
    depends_on:
      - db
    networks:
      - cyber_network
    volumes:
      - cherubimis_website_static:/website/staticfiles


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cherubimis_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - cyber_network
    volumes:
      - /etc/letsencrypt/live/cherubimis.stagging.whitehillscare.co.uk/fullchain.pem:/etc/letsencrypt/live/cherubimis.stagging.whitehillscare.co.uk/fullchain.pem;
      - /etc/letsencrypt/live/cherubimis.stagging.whitehillscare.co.uk/privkey.pem:/etc/letsencrypt/live/cherubimis.stagging.whitehillscare.co.uk/privkey.pem;
      - cherubimis_website_static:/website/staticfiles:ro
volumes:
  db_data:
  

networks:
  cyber_network:
    driver: bridge
